### ISSUE TITLE
The mel spectrogram

### ISSUE THREAD

**Issue by stg1205** [urinieto/harmonixset#12]
Hello,

Why does the pre-calculated mel spectrogram just have one dimension?

**Comment by urinieto** [comment]
It should be 2-dimensional. What URL did you use to get these data?

**Comment by urinieto** [comment]
I just downloaded the file from the link in the readme (https://www.dropbox.com/s/zxnqlx0hxz0lsyc/Harmonix_melspecs.tgz?dl=0) and the melspecs are 2-dimensional:

```python
In [1]: import numpy as np
In [2]: np.load("/Users/onieto/Downloads/Harmonix_melspecs/melspecs/0001_12step-mel.npy").shape
Out[2]: (80, 3066)
```

Maybe your downloading process did not properly finish?

**Comment by stg1205** [comment]
Oh I see. I used np.fromfile to load the data. It's weired that it's one-dimension and also the length is not an integar multiple of n_mels. np.load works well. Thank you for your help!

**Comment by urinieto** [comment]
Yeah, it is not advised to use `fromfile` to read in platform independent npy files (see note here: https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html). 

I'll close this for now.
