### ISSUE TITLE
Window function of the melspectrom

### ISSUE THREAD

**Issue by lzqlzzq** [urinieto/harmonixset#14]
Thanks for the great dataset! I am trying to get the original waveform from the melspectrom so that I can utilize some pre-trained audio encoder. But I followed the `info.json` and `librosa` but it seems to have some weird periodic "envelope" in the inversed signal. I think that maybe related to window function of mel transform. Here is my code:
```
librosa.feature.inverse.mel_to_audio(mel_spec,
                                                sr=info['SR'],
                                                n_fft=info['N_FFT'],
                                                hop_length=info['HOP_LENGTH'],
                                                fmin=info['MEL_FMIN'],
```
I also tried many window function but none of one works. What is the proper way to inverse the melspectrom into signal?

**Comment by urinieto** [comment]
Hi there! Unfortunately computing the inverse melspectogram to obtain waveforms is not supported by the license on which these melspectrograms were released (see the `LICENSE` file in the [tgz](https://www.dropbox.com/s/zxnqlx0hxz0lsyc/Harmonix_melspecs.tgz?dl=0) for more info). If you need different melspec parameters, I can compute a new set of features for you.

**Comment by lzqlzzq** [comment]
Thanks for your rapid reply!
I would like to use these setup for my higher time resolution usage:
```
librosa.feature.melspectrogram(y=y, sr=24000, n_fft=2048, hop_length=512, window='hann', center=True, pad_mode='constant', power=2.0, n_mels=206, fmin=30, fmax=12000)
```

**Comment by urinieto** [comment]
@lzqlzzq , aplogies for the delay! [Here](https://www.dropbox.com/scl/fi/vifot4kxoa06te7rawlao/Harmonixset_librosa_features_20240313.tgz?rlkey=4lzkek2cstzsrvs49yxx6dhff&dl=0) you have the new features!

**Comment by lzqlzzq** [comment]
Much thanks!
