### ISSUE TITLE
The audio I collected does not match the data set

### ISSUE THREAD

**Issue by Sodayeyeye** [urinieto/harmonixset#15]
Hello,
What is done with the acquired audio? Why is it so different from the audio duration in your dataset,The audio I collected does not match the data set. I'm sorry to bother you. I hope you can help me

**Comment by urinieto** [comment]
The audio used for this dataset was modified by Harmonix to accommodate for their games. While the audio is copyrighted, you may obtain audio features from here: https://github.com/urinieto/harmonixset?tab=readme-ov-file#audio-data-updated-december-2020

If you would like to obtain other type of audio features, please post your requirements here.

**Comment by Sodayeyeye** [comment]
Thank you for your reply. Can I get the audio processed by Harmonix? I think this may violate the music copyright issue, if possible, it will help me a lot, thanks again!

**Comment by urinieto** [comment]
We can distribute audio features as long as those are not reversed engineered and used for research (ie, non-commercial) applications.

**Comment by Sodayeyeye** [comment]
I'd like to get mp3 files if I can. One more thing I want to ask, is your beats_and_downbeats dataset generated from code in your src directory? I want to know the process. Thank you again for your patient reply

**Comment by urinieto** [comment]
Unfortunately, we can't distribute the mp3 files. The beats_and_downbeats data was annotated by the experts, as described in the [original publication](https://archives.ismir.net/ismir2019/paper/000068.pdf).

**Comment by nikhilsos** [comment]
> The audio used for this dataset was modified by Harmonix to accommodate for their games. While the audio is copyrighted, you may obtain audio features from here: https://github.com/urinieto/harmonixset?tab=readme-ov-file#audio-data-updated-december-2020
> 
> If you would like to obtain other type of audio features, please post your requirements here.

Would it be possible for you guys to provide the specs in the shapes as requested?

**Comment by urinieto** [comment]
Can you elaborate on the "specs in the shapes" part?

**Comment by nikhilsos** [comment]
I meant mel bins, 
The json says:
"SR": 22050,
"N_MELS": 80, 
If I wanted 128 mel bins, would it be possible to change from 80 or does it have to be recomputed from audio? I am relatively new, so sorry for asking dumb questions..

**Comment by urinieto** [comment]
There's no dumb questions :)

Please, give me the exact specs you want for your melspectrograms and I can compute those for you.

**Comment by nikhilsos** [comment]
Thanks a lot, I'd like to request one with "SR": 22050, "N_MELS": 128.

**Comment by nikhilsos** [comment]
> There's no dumb questions :)
> 
> Please, give me the exact specs you want for your melspectrograms and I can compute those for you.

Thanks, If possible I'd like to get one with these specs,
    "SR": 22050,
    "N_MELS": 81,
    "N_FFT": 2048,
    "HOP_LENGTH": 220,
    "MEL_FMIN": 0,
    "MEL_FMAX": null

**Comment by urinieto** [comment]
Here you have, @nikhilsos https://www.dropbox.com/scl/fi/1lsm7ff3n0u4w00sb9l4p/Harmonixset_librosa_features_20240917.tgz?rlkey=bj91nxi3x9c9xdpwgz1ygft5m&st=wx3nngdy&dl=0 :)
