### ISSUE TITLE
Results differing between paper and repository?

### ISSUE THREAD

**Issue by f90** [urinieto/harmonixset#4]
Hey,

your beat tracking plot in [here](https://github.com/urinieto/harmonixset/blob/master/results/beats/beats.pdf)
shows different results than the one in the [paper](https://ccrma.stanford.edu/~urinieto/MARL/publications/ISMIR2019-Nieto-Harmonix.pdf) - is there a mistake somehow?

**Comment by MCMcCallum** [comment]
Hi,

Good observation! It looks like the Max F-Measure and F-Measure labels have been erroneously switched in the repo. Thanks for catching this, a fix will be made in the coming days.

**Comment by MCMcCallum** [comment]
Note this has been fixed for the next release in the commit here:

https://github.com/urinieto/harmonixset/commit/4425d3181a849fd64483ea11ae965f7e94153e24
