### ISSUE TITLE
Cannot load the mel-scale spectrograms by np.load()

### ISSUE THREAD

**Issue by cruiceble** [urinieto/harmonixset#8]
when using np.load() to load the npy file, the error is :
_pickle.UnpicklingError: invalid load key, '\x00'.
Can anybody help me?

**Comment by urinieto** [comment]
This looks like a Python/Numpy version mismatch. Can you share your system specs and version numbers?

**Comment by cruiceble** [comment]
Windows 10
python 3.6.3
numpy 1.19.3
librosa 0.7.0

**Comment by urinieto** [comment]
Gotcha. Glad to know it's working!
